name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the application (replace with your build/start command)
      - name: Start application
        run: npm run build && npm start &
        env:
          CI: true

      # Wait for the application to be ready on port 3000
      - name: Wait for the application to be ready
        uses: jakejarvis/wait-on-action@v1
        with:
          url: http://localhost:3000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run
