name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies with --legacy-peer-deps flag
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Check if port 3000 is free
      - name: Check if port 3000 is free
        run: |
          if lsof -i :3000; then
            echo "Port 3000 is already in use, failing the job."
            exit 1
          else
            echo "Port 3000 is free."
          fi

      # Start the application in the background
      - name: Start application
        run: npm run build && npm start &
        env:
          CI: true

      # Wait for the application to be ready on localhost:3000
      - name: Wait for application to start
        run: npx wait-on http://localhost:3000 --timeout 120000

      # Check open ports to verify the server is running
      - name: Check open ports
        run: netstat -tuln

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run
