name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build the application
      - name: Build the application
        run: npm run build

      # Start the application in production mode and log output
      - name: Start application
        run: npm start &
        env:
          CI: true
          FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}

      # Wait for the application to start
      - name: Wait for application to start
        run: npx wait-on http://localhost:3000 --timeout 120000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run
