name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies with --legacy-peer-deps flag
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Create .env file with secrets for Firebase configuration
      - name: Create .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env

      # Log Firebase secrets (for debugging)
      - name: Log Firebase secrets (for debugging)
        run: |
          echo "REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}"
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}"
          echo "REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}"

      # Build and start the app
      - name: Build and start the application
        run: |
          npm run build
          npm start &
        env:
          CI: true

      # Wait for the application to start
      - name: Wait for the application to start
        run: npx wait-on http://localhost:3000 --timeout 120000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run

      # (Optional) Print app log for debugging purposes if tests fail
      - name: Print app logs
        if: failure()
        run: cat app.log
